version: 0.2

phases:
  install:
    commands:
      - echo "Nothing heavy to install"
  build:
    commands:
      - echo "Building app..."
      - mkdir -p dist
      - cp -r * dist/ # make sure this doesn't copy dist into itself
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - dist/**/*
